services:
  - type: web
    name: magnetstreamer
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        fromService:
          type: web
          name: magnetstreamer
          property: url
